export const TYPE_VARIANTS: Record<string, "success" | "warning" | "error" | "info"> = {
  USER_CREATED: "success",
  USER_UPDATED: "warning",
  USER_DELETED: "error",
  USER_DEACTIVATED: "error",
  USER_REACTIVATED: "success",
  USER_ASSIGNED_MENTOR: "success",
  USER_GRANTED_SERVER_ACCESS: "success",
  USER_REVOKED_SERVER_ACCESS: "error",
  SERVER_CREATED: "success",
  SERVER_UPDATED: "warning",
  SERVER_DELETED: "error",
  SERVER_AVAILABLE: "success",
  SERVER_UNAVAILABLE: "error",
  RESERVATION_CREATED: "info",
  RESERVATION_AVAILABLE: "info",
  RESERVATION_EXTENDED: "info",
  RESERVATION_COMPLETED: "success",
  RESERVATION_CANCELLED: "error",
};

export const TYPE_TRANSLATIONS: Record<string, string> = {
  USER_CREATED: "Usuario creado",
  USER_UPDATED: "Usuario actualizado",
  USER_DELETED: "Usuario eliminado",
  USER_DEACTIVATED: "Usuario desactivado",
  USER_REACTIVATED: "Usuario reactivado",
  USER_ASSIGNED_MENTOR: "Usuario asignado a mentor",
  USER_GRANTED_SERVER_ACCESS: "Acceso a servidor concedido",
  USER_REVOKED_SERVER_ACCESS: "Acceso a servidor revocado",
  SERVER_CREATED: "Servidor creado",
  SERVER_UPDATED: "Servidor actualizado",
  SERVER_DELETED: "Servidor eliminado",
  SERVER_AVAILABLE: "Servidor disponible",
  SERVER_UNAVAILABLE: "Servidor no disponible",
  RESERVATION_CREATED: "Reserva creada",
  RESERVATION_AVAILABLE: "Reserva disponible",
  RESERVATION_EXTENDED: "Reserva extendida",
  RESERVATION_COMPLETED: "Reserva completada",
  RESERVATION_CANCELLED: "Reserva cancelada",
};