name: "⚙️ configuration: Cambios de Configuración"
description: "Solicitar cambios en la configuración del proyecto."
title: "[Chore] "
labels: ["configuration"]
body:
  - type: markdown
    attributes:
      value: |
        # **⚙️ configuration: Cambios de Configuración**

  - type: textarea
    id: configuration-description
    attributes:
      label: "Descripción del Cambio"
      description: "Explica los cambios de configuración necesarios y cómo impactan al proyecto en términos de funcionalidad, rendimiento, etc."
    validations:
      required: true

  - type: textarea
    id: configuration-modules
    attributes:
      label: "Módulos Afectados"
      description: "Lista los módulos o áreas del proyecto que se verán afectados por el cambio de configuración."
    validations:
      required: true
      
  - type: textarea
    id: configuration-comments
    attributes:
      label: "Comentarios Adicionales"
      description: "Añade cualquier contexto o comentario adicional que pueda ser útil para comprender mejor los cambios propuestos."
    validations:
      required: false
