name: "📦 feat: Nueva Funcionalidad"
description: "Solicita una nueva funcionalidad para el proyecto."
title: "[Feature] "
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        # **📦 feat: Nueva Funcionalidad**
  
  - type: textarea
    id: feature-description
    attributes:
      label: "Descripción de la Nueva Funcionalidad"
      description: "Explica la nueva funcionalidad requerida y cómo impacta el proyecto."
    validations:
      required: true

  - type: textarea
    id: affected-modules
    attributes:
      label: "Módulos Afectados"
      description: "Lista de los módulos afectados por la nueva funcionalidad."
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: "Comentarios Adicionales"
      description: "Cualquier comentario adicional que desees agregar sobre la nueva funcionalidad."
    validations:
      required: false
