name: "🐛 fix: Corrección de Error"
description: "Informa un error para ayudar a mejorar el proyecto."
title: "[Fix] "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: |
        # **🐛 fix: Corrección de Error**
  
  - type: textarea
    id: error-description
    attributes:
      label: "Descripción del Error"
      description: "Explica el error que encontraste y su impacto. Proporciona una descripción clara y concisa del problema."
    validations:
      required: true

  - type: textarea
    id: affected-modules
    attributes:
      label: "Módulos Afectados"
      description: "Lista de los módulos afectados por el error."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Pasos para Reproducir"
      description: "Escribe los pasos detallados para reproducir el error."
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: "Comentarios Adicionales"
      description: "Añade cualquier comentario adicional o contexto sobre el error."
    validations:
      required: false
