name: Codacy CI

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true

jobs:

  codacy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install pnpm
      run: npm install -g pnpm
        
    - name: Install dependencies
      run: |
        pnpm store prune
        pnpm install

    - name: Test and coverage
      run: pnpm jest --coverage

    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info